services:
  - type: web
    name: shred-running-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /health
    autoDeploy: true 